### ISSUE TITLE
No location specified for config.yaml

### ISSUE THREAD

**Issue by rogertetzlaff** [Eurotimmy/unraid-templates#1]
The template doesn't have an entry for a config directory, and no config.yml is created under the /mnt/user/appdata/romm/ directory tree.

Modifying config.yml is the way ROMM usually works, for things like mapping custom library paths to supported platforms, however if I execute a shell in the running container (which means looking at the underlying disk from the docker daemon, not the user-modifiable appdata directory), I only see /backend/config/tests/fixtures/config.yml ... which is marked internally as a test/sample file only.

Can someone fill me in on the missing piece here? Is the "test" config.yml actually live, so if I create a manual mount path for /backend/config/tests/fixtures/ in unraid's docker config for romm, it will allow me to create and modify my own config? Should I create a configmap for config.yml to mount at /backend/config/config.yml in the container, which will override any default configuration?

**Comment by Eurotimmy** [comment]
Config file location updated and additional notes in the support thread
