### ISSUE TITLE
8080 very common - Consider a new default port for exposed web port 

### ISSUE THREAD

**Issue by rogertetzlaff** [Eurotimmy/unraid-templates#2]
Request to change the http port to something less common. Dozens of other web app containers default to 8080 / 8443 for http/https. Internally the container target port defaults to 8080, but for example, zurdi15's template for this container uses an external web port of 8091. This will make the template more easily integrated to a wider array of unraid users who don't want to change the default port.

**Comment by Squidly271** [comment]
That's not an issue.  You simply change the host port....

**Comment by Eurotimmy** [comment]
The template was adjusted slightly to ensure Unraid CA has no warnings and the user can adjust the port to their liking.

**Comment by Eurotimmy** [comment]
.
