### ISSUE TITLE
Needs ability to set page size

### ISSUE THREAD

**Issue by radiatewishbone** [Eurotimmy/unraid-templates#9]
For me, this tool is currently unusable for one key reason: it seems to be impossible to set a defined page size, which the CV conforms to.

I often like to print my CVs out, and I use A4 paper with my printer. Currently, I basically am forced to guess how long each page of my CV is.

Also, if I want to add a lot more work experience, or any other sub-element, it seems I have to basically guess where the second A4 would begin, and then create another section (also called "Work Experience") and then drag that module over to the second page. 

Why can't the tool automatically start writing to the next page, based on how much space is left on the existing page and the pre-defined desired page size?

**Comment by Eurotimmy** [comment]
Hi @a-laurence-uk, 
I'm maintaining the template for Unraid users to install the Reactive Resume tool in Unraid, but not the tool itself.
Please take a look at "https://github.com/AmruthPillai/Reactive-Resume".
Amruth Pillai is the developer and maintains the features etc.
Cheers
